server:
  port: 80
spring:
  application:
    name: apigateway-service
#  globalcors:
#      cors-configurations:
#        '[/**]':
#          allowedOrigins: "https://docs.spring.io"
#          allowedMethods:
#          - GET

  cloud:
    gateway:
      routes:
        - id: userId
          uri: http://localhost:5555
          predicates:
            - Path=/users/**
        - id: projectId
          uri: http://localhost:5556
          predicates:
            - Path=/projects/**
