server:
  port: 5557
  
spring:
  application:
    name: FRONT-SERVICE
#  main:
#    web-application-type: reactive   

# 공개된 eureka server에 등록
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka

# 구분 id
  instance:
    instance-id: ${spring.application.name}:${server.port}

