server:
  port: 5555
spring:
  application:
    name: user-service

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

# 구분 id
  instance:
    instance-id: ${spring.application.name}:${server.port}