server:
  port: 5556
  
spring:
  application:
    name: PROJECT-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: user01
    username: user01
    url: jdbc:mysql://127.0.0.1:8777/fisa?useSSL=false&allowPublicKeyRetrieval=true
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: true
  mvc:        # jsp 사용을 위한 필수 설정, WEB-INF 폴더 직접 만들고, pom.xml에 설정, ProbonoController의 메소드 setViewName()확인하기
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  logging:
    level:
      springboot.MVCBasic: debug  
    
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}

      
 
        
    